# Generated by Django 6.0.2 on 2026-02-26 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('data', models.DateTimeField()),
                ('posti_disponibili', models.PositiveIntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='corsi/')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prenotazione', models.DateTimeField(auto_now_add=True)),
                ('attiva', models.BooleanField(default=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corsi.corso')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
