# Generated by Django 6.0.2 on 2026-03-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='in_lista_attesa',
            field=models.BooleanField(default=False),
        ),
    ]
