# Generated by Django 6.0.2 on 2026-03-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0003_prenotazione_in_lista_attesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='tipologia',
            field=models.CharField(default='Yoga', max_length=50),
            preserve_default=False,
        ),
    ]
