# Generated by Django 6.0.2 on 2026-03-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0005_rename_profile_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='immagine_profilo',
            field=models.ImageField(upload_to='profili/'),
        ),
    ]
