# Generated by Django 6.0.2 on 2026-03-11 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corsi', '0006_alter_profilo_immagine_profilo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilo',
            new_name='Profile',
        ),
    ]
